// Generated by CoffeeScript 1.12.2
(function() {
  var Connection, connections, i, server, settings;

  server = require('./web.js');

  Connection = require('./redCamera.js');

  connections = [];

  settings = {
    'nrOfConnections': 10
  };

  i = 1;

  while (i <= settings.nrOfConnections) {
    connections[i] = new Connection();
    connections[i].on('data', function(data) {
      return console.log("app.js " + (connections.indexOf(this)) + " (data): " + data);
    });
    connections[i].on('status', function(data) {
      return console.log("app.js " + (connections.indexOf(this)) + " (status): " + data);
    });
    connections[i].on('statusVB', function(data) {
      return console.log("app.js " + (connections.indexOf(this)) + " (statusVB): " + data);
    });
    i++;
  }

  server.start(connections, settings);

  process.stdin.setEncoding('utf8');

  process.stdin.on('readable', (function(_this) {
    return function() {
      var chunk;
      chunk = process.stdin.read();
      if (chunk !== null) {
        chunk = chunk.replace("\n", "");
        return camera2.sendCommand(chunk);
      }
    };
  })(this));

}).call(this);
