// Generated by CoffeeScript 1.12.2
(function() {
  var app, express;

  express = require('express');

  app = express();

  module.exports = {
    start: function(cameras) {
      app.get('/connect1', function(req, res) {
        cameras[1].connect('127.0.0.1', true, 0, 8888);
        return res.end("connecting1\n");
      });
      app.get('/connect2', function(req, res) {
        cameras[2].connect('127.0.0.1', true, 0, 8889);
        return res.end("connecting2\n");
      });
      app.get('/disconnect1', function(req, res) {
        cameras[1].disconnect();
        return res.end("disconnecting1\n");
      });
      app.get('/disconnect2', function(req, res) {
        cameras[2].disconnect();
        return res.end("disconnecting2\n");
      });
      return app.listen(3000, function() {
        return console.log('Example app listening on port 3000!');
      });
    }
  };

}).call(this);
